# Generated by Django 2.2.6 on 2019-12-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on'], 'permissions': (('create_post', 'Can create post'), ('edit_post', 'Can edit post'))},
        ),
    ]
