# Generated by Django 3.0.2 on 2020-04-02 23:58

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.FileField(blank=True, upload_to=blog.models.user_directory_path),
        ),
    ]
